<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tidak mempunyai akun</name>
   <tag></tag>
   <elementGuidId>547fc41d-880f-4f32-a465-7f87d01f2ccd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='formLogin-id']/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.form-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>31e02b72-18ba-4272-a634-acc67b8c0a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/register</value>
      <webElementGuid>2a915c70-0721-4f97-bc95-82a7ec90886c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-text</value>
      <webElementGuid>e8786c3a-5aec-43e1-acb1-aba7506af4e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tidak mempunyai akun!?</value>
      <webElementGuid>752113a2-95b6-482d-ae91-b133353bcab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formLogin-id&quot;)/div[@class=&quot;mb-3&quot;]/a[@class=&quot;form-text&quot;]</value>
      <webElementGuid>cadc15f1-c67b-40f3-8a25-d752f7278bca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formLogin-id']/div[3]/a</value>
      <webElementGuid>c133066b-480e-4d08-abd3-3dde451e5c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tidak mempunyai akun!?')]</value>
      <webElementGuid>b3d5d972-a333-4b9b-84e9-17e0d8597641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>bf726c53-cf22-4f72-b1f3-ac6b33825baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/register')]</value>
      <webElementGuid>4fcb228e-0f5e-47bd-933f-e8b5859d616e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>67db27c0-3b5f-40bd-955f-bd24d053c3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/register' and (text() = 'Tidak mempunyai akun!?' or . = 'Tidak mempunyai akun!?')]</value>
      <webElementGuid>a019d06c-59c3-4781-8020-91c8764641d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tidak mempunyai akun!?']/parent::*</value>
      <webElementGuid>48a569e5-2371-462b-9b76-f50d3d92f9e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
