<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SignOut_rounded-circle position-fixed b_a96560</name>
   <tag></tag>
   <elementGuidId>081b2680-4f4e-43d1-9deb-901cdf50a788</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Upload']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle.position-fixed.bottom-0.end-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7b4ef5ce-8294-4c7d-a5e5-d803d7c3f238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./Image/Timeline/UploadIcon-removebg-preview.png</value>
      <webElementGuid>99c90047-b59b-4882-9629-efcddd252cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Upload</value>
      <webElementGuid>5194728c-79b3-42d8-8363-50867c53acea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle position-fixed bottom-0 end-0</value>
      <webElementGuid>8d8e04ae-c365-4a2c-93dc-f51405bae3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/footer[1]/div[@class=&quot;position-relative&quot;]/a[1]/img[@class=&quot;rounded-circle position-fixed bottom-0 end-0&quot;]</value>
      <webElementGuid>cf303fb3-1548-434b-8b7c-e79107eb6bbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Upload']</value>
      <webElementGuid>10f6e466-f6a6-47f4-98d1-5b18855eeccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/a/img</value>
      <webElementGuid>06b2e676-8f06-4d5c-a3e6-2758de10c99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './Image/Timeline/UploadIcon-removebg-preview.png' and @alt = 'Upload']</value>
      <webElementGuid>96a6f85b-c116-42ce-a5f7-80440218d53a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
