name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      working-directory: laravel
    - name: update composer
      run: composer update
      working-directory: laravel
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      working-directory: laravel
    - name: Generate key
      run: php artisan key:generate
      working-directory: laravel
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      working-directory: laravel
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Download Katalon Studio
      run: |
        wget -O Katalon_Studio.tar.gz "https://download.katalon.com/7.9.0/Katalon_Studio_Linux.tar.gz"
        tar xvzf Katalon_Studio.tar.gz
    - name: Execute Katalon Studio tests
      run: ./Katalon_Studio/katalonc.sh -runMode=console -projectPath=path/to/your/project -reportFolder=KatalonReports -browserType="Chrome" -apiKey=your_api_key

      # Archive Katalon test reports as artifact
    - name: Archive Katalon Test Reports
      uses: actions/upload-artifact@v2
      with:
        name: Katalon-Test-Reports
        path: Katalon_Studio/KatalonReports
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
      working-directory: laravel
